site:
  title: My Documentation
  start_page: user_manual::index.adoc
  
content:
  sources:
    - url: .
      branches: [HEAD]
      start_path: docs

ui:
  bundle:
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    url: ./build/ui-bundle.zip   
    snapshot: true

asciidoc:
  attributes:
    page-pagination: ''