site:
  title: INTERLIS // Dokumentation
  start_page: user_manual::userhb24/userhb_index.adoc
  
content:
  sources:
    - url: .
      branches: [HEAD]
      start_path: docs/user_manual
    - url: .
      branches: [HEAD]
      start_path: docs/ref_manual

ui:
  bundle:
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    url: ./bundle/ui-bundle.zip   
    snapshot: true
  supplemental_files: ./supplemental-ui

asciidoc:
  attributes:
    page-pagination: ''
    kroki-fetch-diagram: true    
    lang: de
    section-refsig: 'Kapitel'
    table-caption: Tabelle@
    example-caption: Beispiel@
    figure-caption: Abbildung@
    important-caption: Wichtig@
    last-update-label: Zuletzt aktualisiert@
    listing-caption: Listing@
    manname-title: Name@
    note-caption: Hinweis@
    preface-title: Vorwort@
    caution-caption: Achtung@
    tip-caption: Tipp@
    warning-caption: Warnung@
    untitled-label: Ohne Titel@
    version-label: Version@
    page-toctitle: Inhalt@    
  extensions:
    - asciidoctor-kroki

antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true    
      languages: [de]    